import { chromium } from 'playwright';
const b = await chromium.launch();
const pg = await b.newPage({ viewport: { width: 1200, height: 1400 } });
await pg.goto('https://www.sagareus.com/wt', { waitUntil: 'domcontentloaded', timeout: 60000 });
await pg.waitForSelector('[id^="saga-pr-spolish"]', { timeout: 30000 });
console.log('initial:', await pg.$eval('[id^="saga-pr-spolish"]', e => ({ label: e.textContent.trim(), disabled: e.disabled })));
await pg.fill('[id^="saga-pr-semail"]', 'bbfrench206@gmail.com');
await pg.click('[id^="saga-pr-slk"]');
await pg.waitForFunction(() => { const e = document.querySelector('[id^="saga-pr-chips"]'); return e && e.children.length > 0; }, { timeout: 25000 });
const rough = 'i looked at the comps around the area and honestly i think 2895 is teh right number, the market is prety active rite now and simlar homes r leasing fast, we shud list quick to catch august movers';
await pg.fill('[id^="saga-pr-scomments"]', rough);
await pg.dispatchEvent('[id^="saga-pr-scomments"]', 'input');
await pg.waitForTimeout(200);
console.log('after typing:', await pg.$eval('[id^="saga-pr-spolish"]', e => ({ label: e.textContent.trim(), disabled: e.disabled })));
await pg.click('[id^="saga-pr-spolish"]');
await pg.waitForFunction(() => { const t = document.querySelector('[id^="saga-pr-scomments"]'); return t && !/teh right number/.test(t.value); }, { timeout: 45000 });
console.log('POLISHED:', await pg.$eval('[id^="saga-pr-scomments"]', e => e.value));
console.log('button after:', await pg.$eval('[id^="saga-pr-spolish"]', e => e.textContent.trim()));
await b.close();
