import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { COMPANY } from "@/lib/constants";
import { EBOOKS, getEbook } from "@/lib/ebooks";
import { BONUS_TIP, ESSENTIAL_QUESTIONS } from "@/lib/essentials";
import { getCluster, getClusterGuides, getPillar } from "@/lib/guides";
import type { Guide } from "@/lib/guides/types";

// Print-only source for the downloadable ebooks. Not linked anywhere,
// noindexed, and disallowed in robots.ts. Rendered to PDF by
// scripts/generate-ebooks.mjs.

export function generateStaticParams() {
  return EBOOKS.map((e) => ({ cluster: e.clusterId }));
}

export const metadata: Metadata = {
  robots: { index: false, follow: false },
};

/** Use the print-resolution JPEGs generated by scripts/generate-ebooks.mjs
 *  (JPEG embeds compactly in PDFs; WebP gets re-encoded losslessly and
 *  bloats the file). */
function opt(src: string) {
  const base = src.split("/").pop()!.replace(/\.(webp|jpeg|jpg|png)$/i, "");
  return `/print-images/${base}.jpg`;
}

/** Render [text](href) as plain styled text with absolute, clickable URLs. */
function renderInline(text: string) {
  const parts = text.split(/(\[[^\]]+\]\([^)]+\))/g);
  return parts.map((part, i) => {
    const match = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
    if (!match) return part;
    const href = match[2].startsWith("http")
      ? match[2]
      : `${COMPANY.url}${match[2]}`;
    return (
      <a key={i} href={href} style={{ color: "#d85024", fontWeight: 500, textDecoration: "none" }}>
        {match[1]}
      </a>
    );
  });
}

function Chapter({ guide, number }: { guide: Guide; number: number }) {
  return (
    <section style={{ breakBefore: "page" }}>
      <p className="text-xs font-semibold uppercase tracking-widest text-[#d85024] mb-2 pt-2">
        Chapter {number}
      </p>
      <h2 className="text-3xl font-bold text-[#092e5e] leading-tight mb-5">
        {guide.title}
      </h2>
      <div className="space-y-3 mb-6">
        {guide.intro.map((p, i) => (
          <p key={i} className="text-[15px] leading-relaxed text-[#3e3d3b]">
            {renderInline(p)}
          </p>
        ))}
      </div>
      {guide.sections.map((s, i) => (
        <div key={i} style={{ breakInside: "avoid-page" }} className="mb-6">
          <h3 className="text-xl font-semibold text-[#092e5e] mb-2">
            {s.heading}
          </h3>
          <div className="space-y-3">
            {s.paragraphs.map((p, j) => (
              <p key={j} className="text-[15px] leading-relaxed text-[#3e3d3b]">
                {renderInline(p)}
              </p>
            ))}
          </div>
          {s.bullets && (
            <ul className="mt-3 space-y-2">
              {s.bullets.map((b, j) => (
                <li key={j} className="flex gap-2">
                  <span className="mt-[7px] h-[6px] w-[6px] flex-shrink-0 rounded-full bg-[#ffbd59]" />
                  <span className="text-[15px] leading-relaxed text-[#3e3d3b]">
                    {renderInline(b)}
                  </span>
                </li>
              ))}
            </ul>
          )}
          {s.image && (
            <div className="mt-4" style={{ breakInside: "avoid-page" }}>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={opt(s.image.src)}
                alt={s.image.alt}
                style={{ width: "70%", borderRadius: 8 }}
              />
              <p className="text-xs text-[#9a9895] mt-1">{s.image.alt}</p>
            </div>
          )}
        </div>
      ))}
      <div style={{ breakInside: "avoid-page" }} className="mt-8 rounded-xl border border-[#e5e0d6] bg-[#f5f1ea] p-5">
        <h3 className="text-lg font-semibold text-[#092e5e] mb-3">
          Quick answers
        </h3>
        <div className="space-y-3">
          {guide.faqs.map((f, i) => (
            <div key={i}>
              <p className="text-[15px] font-semibold text-[#092e5e]">
                {f.question}
              </p>
              <p className="text-[14px] leading-relaxed text-[#3e3d3b]">
                {f.answer}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default async function EbookPrintPage({
  params,
}: {
  params: Promise<{ cluster: string }>;
}) {
  const { cluster: clusterId } = await params;
  const ebook = getEbook(clusterId);
  const cluster = getCluster(clusterId);
  if (!ebook || !cluster) notFound();

  const pillar = getPillar(clusterId);
  const supporting = getClusterGuides(clusterId).filter((g) => !g.isPillar);
  const chapters = pillar ? [pillar, ...supporting] : supporting;

  return (
    <div className="ebook bg-white text-[#3e3d3b]" style={{ fontFamily: "var(--font-inter), Inter, sans-serif" }}>
      {/* Hide site chrome in the rendered PDF */}
      <style>{`
        header, footer, [data-reviews-widget] { display: none !important; }
        @page { size: Letter; }
      `}</style>

      {/* ── Cover ── */}
      <section
        className="flex flex-col justify-between bg-[#092e5e] text-white p-14"
        style={{ height: "9.6in", breakAfter: "page" }}
      >
        <div>
          <span className="inline-block rounded-lg bg-white px-5 py-4">
            <Image
              src="/images/logo.png"
              alt="French Roofing"
              width={180}
              height={103}
            />
          </span>
        </div>
        <div>
          <p className="text-[#ffbd59] font-semibold text-sm uppercase tracking-widest mb-4">
            An Oregon Roofing Guide
          </p>
          <h1 className="text-6xl font-bold leading-tight mb-6">{ebook.title}</h1>
          <p className="text-xl text-gray-300 max-w-xl leading-relaxed">
            {ebook.subtitle}
          </p>
        </div>
        <div className="relative" style={{ height: "2.9in" }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={opt(ebook.coverImage)}
            alt=""
            style={{ width: "100%", height: "100%", objectFit: "cover", borderRadius: 8 }}
          />
        </div>
        <p className="text-sm text-gray-400 pt-6">
          {COMPANY.name} &middot; Damascus, OR &middot; {COMPANY.phone} &middot;
          CCB #{COMPANY.ccb} &middot; frenchroofing.com
        </p>
      </section>

      {/* ── Contents ── */}
      <section className="p-16" style={{ breakAfter: "page" }}>
        <h2 className="text-3xl font-bold text-[#092e5e] mb-2">
          What&apos;s inside
        </h2>
        <p className="text-[15px] text-[#6b6a67] mb-8">
          Written by the French Roofing crew in Damascus, Oregon. Family-owned
          since 2014, CertainTeed Certified, and licensed, insured, and bonded
          (CCB #{COMPANY.ccb}).
        </p>
        <ol className="space-y-3">
          {chapters.map((g, i) => (
            <li key={g.slug} className="flex gap-4 items-baseline">
              <span className="text-[#d85024] font-bold text-lg w-7 text-right flex-shrink-0">
                {i + 1}
              </span>
              <span className="text-[17px] font-medium text-[#092e5e]">
                {g.title}
              </span>
            </li>
          ))}
          {ebook.includeEssentials && (
            <li className="flex gap-4 items-baseline">
              <span className="text-[#d85024] font-bold text-lg w-7 text-right flex-shrink-0">
                {chapters.length + 1}
              </span>
              <span className="text-[17px] font-medium text-[#092e5e]">
                10 Essential Questions to Ask Every Roofing Contractor
              </span>
            </li>
          )}
        </ol>
      </section>

      {/* ── Chapters ── */}
      <div className="px-16 pb-16">
        {chapters.map((g, i) => (
          <Chapter key={g.slug} guide={g} number={i + 1} />
        ))}

        {/* ── Essentials chapter (Replacement Guide only) ── */}
        {ebook.includeEssentials && (
          <section style={{ breakBefore: "page" }}>
            <p className="text-xs font-semibold uppercase tracking-widest text-[#d85024] mb-2 pt-2">
              Chapter {chapters.length + 1}
            </p>
            <h2 className="text-3xl font-bold text-[#092e5e] leading-tight mb-5">
              10 Essential Questions to Ask Every Roofing Contractor
            </h2>
            <p className="text-[15px] leading-relaxed mb-6">
              Choosing the right roofing contractor is crucial for the success
              of your project. We put this list together because we believe
              informed homeowners make better decisions. Whether you hire
              French Roofing or someone else, these questions will help you
              hire with confidence. Ask them of every contractor who quotes
              your roof, including us.
            </p>
            {ESSENTIAL_QUESTIONS.map((q) => (
              <div key={q.number} style={{ breakInside: "avoid-page" }} className="mb-5">
                <h3 className="text-lg font-semibold text-[#092e5e] mb-1">
                  {q.number}. &ldquo;{q.question}&rdquo;
                </h3>
                <p className="text-[15px] leading-relaxed">{q.answer}</p>
              </div>
            ))}
            <div style={{ breakInside: "avoid-page" }} className="rounded-xl border-2 border-[#ffbd59] bg-[#f5f1ea] p-5 mt-6">
              <h3 className="text-lg font-semibold text-[#092e5e] mb-1">
                Bonus: &ldquo;{BONUS_TIP.question}&rdquo;
              </h3>
              <p className="text-[15px] leading-relaxed">{BONUS_TIP.answer}</p>
            </div>
          </section>
        )}

        {/* ── Back page ── */}
        <section
          style={{ breakBefore: "page" }}
          className="rounded-2xl bg-[#092e5e] text-white p-12 mt-4 text-center"
        >
          <h2 className="text-3xl font-bold mb-4">
            Questions About Your Roof?
          </h2>
          <p className="text-lg text-gray-300 mb-6 max-w-lg mx-auto">
            Schedule a FREE roof assessment with French Roofing. We&apos;ll
            evaluate, diagnose, and give you honest options, with photos and a
            written estimate.
          </p>
          <p className="text-2xl font-bold text-[#ffbd59] mb-2">
            frenchroofing.com
          </p>
          <p className="text-lg text-gray-300">{COMPANY.phone}</p>
          <p className="mt-6 text-sm text-gray-400">
            {COMPANY.name} &middot; Damascus, OR {COMPANY.address.zip} &middot;
            Licensed, insured &amp; bonded &middot; CCB #{COMPANY.ccb} &middot;
            CertainTeed Certified &middot; Family-owned since{" "}
            {COMPANY.foundingYear}
          </p>
        </section>
      </div>
    </div>
  );
}
